[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-app-name.onrender.com"
  REACT_APP_WS_URL = "wss://your-backend-app-name.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 